# Generated by Django 4.2.7 on 2023-12-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='get_kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.CharField(max_length=100)),
                ('product_Name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='get_mens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.CharField(max_length=100)),
                ('product_Name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='get_women',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.CharField(max_length=100)),
                ('product_Name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_details', models.CharField(max_length=100)),
            ],
        ),
    ]
